---
- hosts: localhost
  connection: local
  become: true

  roles:
    - workstation
    
  tasks:
  - name: install base utils
    package:
      name:
        - htop
        - tmux
        - screen
        - nmap
        - gnome-tweaks
        - python3-psutil
        - python3-pip
        - code
        - steam-installer

  - name: install flatpaks
    become_user: wdmcquinn
    flatpak:
      name: flathub com.ultimaker.cura
      method: user
      state: present

  - name: set wallpaper
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/pop/nick-nazzaro-underwater.png'"

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/wdmcquinn/ansible_desktop.git

