---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install base utils
    package:
      name:
        - htop
        - tmux
        - screen
        - nmap
        - gnome-tweaks
        - python3-psutil
        - python3-pip

  - name: set wallpaper
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/pop/nick-nazzaro-underwater.png'"



