---
- hosts: localhost
  connection: local
  become: true

  roles:
    - workstation
  #  - role: artis3n.tailscale.machine
  #    vars:
  #      tailscale_up_skip: true
  tasks:
  - name: install base utils
    package:
      name:
        - htop
        - tmux
        - screen
        - nmap
 
  - name: add ansible user
    user:
      name: ansible_adm
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_ansible_adm
      dest: /etc/sudoers.d/ansible_adm
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_adm
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/wdmcquinn/ansible_desktop.git
