---
- hosts: localhost
  connection: local
  become: true

  roles:
    - workstation
    
  tasks:
  - name: install base utils
    package:
      name:
        - htop
        - tmux
        - screen
        - nmap
        - gnome-tweaks
        - python3-psutil
        - python3-pip
        - code
        - steam-installer

  - name: install flatpaks
    become_user: wdmcquinn
    community.general.flatpak:
      name: com.ultimaker.cura
      method: user
      remote: flathub

  - name: set dark mode
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
  
  - name: set theme
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Pop-dark'"

  - name: set font scaling
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/interface/text-scaling-factor"
      value: "1.3000000000000003"

  - name: set dash-to-dock preferences
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock"
      value: "dash-max-icon-size=60"

  - name: set dash-to-dock preferences
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/shell/extensions/dash-to-dock"
      value: "intellihide=true"

  - name: set wallpaper
    become_user: wdmcquinn
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/pop/nick-nazzaro-underwater.png'"

  - name: Activate Numlock
    become_user: wdmcquinn
    dconf:
      key: '/org/gnome/desktop/peripherals/keyboard/numlock-state'
      value: 'true'

  - name: Disable screen lock
    become_user: wdmcquinn
    dconf:
      key: '/org/gnome/desktop/screensaver/lock-enabled'
      value: 'false'

  - name: Disable automatic sleep
    become_user: wdmcquinn
    dconf:
      key: '/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type'
      value: "'nothing'"

  - name: Set favorite apps if not set
    become_user: wdmcquinn
    dconf:
      key: '/org/gnome/shell/favorite-apps'
      value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'code.desktop']"

  - name: add ansible user
    user:
      name: velociraptor
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/wdmcquinn/ansible_desktop.git

